### ISSUE TITLE
Senz3D DepthSense::StreamingException

### ISSUE THREAD

**Issue by JoernR** [ipa320/softkinetic#48] opened 2015-06-10 15:20 UTC
Hi,

I have installed the DepthSense SDK and I can view the image stream with the sample program from the SDK. But I get a "DepthSense::StreamingException" when I start the softkinetic node. I get this error with every color_frame_format setting. If I disable the color image in the config the nodes starts without error. So it has something to do with the color image stream. I use ros indigo on a system with ubuntu 14.04.2 and tried USB 3.0 and 2.0 ports.

Here is the console output from softkinetic_camera_ds325.launch:

```
pmsr@rts-sim-3:~/ros_workspace/catkin_ws/src/ros_depthsense_camera/launch$ roslaunch softkinetic_camera softkinetic_camera_ds325.launch 
... logging to /home/pmsr/.ros/log/3418d49a-0549-11e5-a9b4-d8cb8a4f9f37/roslaunch-rts-sim-3-13950.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://rts-sim-3:44319/

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.13
 * /softkinetic_camera/camera_link: softkinetic_camer...
 * /softkinetic_camera/color_compression: MJPEG
 * /softkinetic_camera/color_frame_format: WXGA
 * /softkinetic_camera/color_frame_rate: 25
 * /softkinetic_camera/confidence_threshold: 200
 * /softkinetic_camera/depth_frame_format: QVGA
 * /softkinetic_camera/depth_frame_rate: 25
 * /softkinetic_camera/depth_mode: close
 * /softkinetic_camera/enable_color: True
 * /softkinetic_camera/enable_depth: True
 * /softkinetic_camera/min_neighbours: 50
 * /softkinetic_camera/search_radius: 0.05
 * /softkinetic_camera/use_radius_outlier_filter: False
 * /softkinetic_camera/use_voxel_grid_filter: False
 * /softkinetic_camera/voxel_grid_size: 0.03

NODES
  /
    softkinetic_camera (softkinetic_camera/softkinetic_bringup_node)

auto-starting new master
process[master]: started with pid [13962]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 3418d49a-0549-11e5-a9b4-d8cb8a4f9f37
process[rosout-1]: started with pid [13975]
started core service [/rosout]
process[softkinetic_camera-2]: started with pid [13992]
[ INFO] [1432824767.747549238]: Number of Devices found: 1
Argument Exception: argument "node": context already has control over the node
terminate called after throwing an instance of 'DepthSense::StreamingException'
  what():  VIDIOC_STREAMON failed (No space left on device)
[softkinetic_camera-2] process has died [pid 13992, exit code -6, cmd /home/pmsr/ros_workspace/catkin_ws/devel/lib/softkinetic_camera/softkinetic_bringup_node 0 __name:=softkinetic_camera __log:=/home/pmsr/.ros/log/3418d49a-0549-11e5-a9b4-d8cb8a4f9f37/softkinetic_camera-2.log].
log file: /home/pmsr/.ros/log/3418d49a-0549-11e5-a9b4-d8cb8a4f9f37/softkinetic_camera-2*.log
```

**Comment by corot** [comment] 2015-06-10 19:55
I cannot reproduce the problem.... same parameters, same version and for me works both with USB 2 and 3. Did you tried exactly the same configuration (color_compression: MJPEG and color_frame_format : WXGA) on the DepthSenseViewer tool? And do you use the las version of the driver? Finally, are you using 32 or 64 bits linux? desktop or laptop?

**Comment by manuelvolk** [comment] 2015-10-14 15:01
Hey there we have the same issue. Same configuration on a desktop computer with ubuntu 14.04.2 64-bit. For USB 2.0 there is a workaround available http://www.softkinetic.com/support/Forum/aft/1735

At the moment I not be able to find the real issue behind this error, because the audio stream is not in use. (I had only a short look at the ros topics)

**Comment by mgruhler** [comment] 2016-06-23 07:00
This seems to be a softkinetic/HW/non-ROS problem, thus I'll close this one.

**Closed as completed by mgruhler** 2016-06-23 07:00 UTC
